"""add media stories reels and live

Revision ID: 0d7191da1ea6
Revises: ae0369e8e812
Create Date: 2026-10-07 00:30:39.058209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7191da1ea6'
down_revision: Union[str, Sequence[str], None] = 'ae0369e8e812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('thumbnail_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("media_type IN ('image', 'video', 'audio')", name='ck_media_assets_media_type'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'ready', 'failed', 'deleted')", name='ck_media_assets_status'),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms > 0', name='ck_media_assets_duration_positive'),
    sa.CheckConstraint('file_size > 0', name='ck_media_assets_file_size_positive'),
    sa.CheckConstraint('height IS NULL OR height > 0', name='ck_media_assets_height_positive'),
    sa.CheckConstraint('width IS NULL OR width > 0', name='ck_media_assets_width_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_provider', 'storage_key', name='uq_media_assets_storage_location')
    )
    op.create_index('ix_media_assets_owner_created', 'media_assets', ['owner_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_media_assets_status_created', 'media_assets', ['status', 'created_at'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.String(length=16), server_default='public', nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("visibility IN ('public', 'followers')", name='ck_stories_visibility'),
    sa.CheckConstraint('text_content IS NULL OR length(text_content) <= 5000', name='ck_stories_text_content_length'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stories_author_created', 'stories', ['author_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_stories_expires_at', 'stories', ['expires_at'], unique=False)
    op.create_table('live_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default='public', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='scheduled', nullable=False),
    sa.Column('streaming_provider', sa.String(length=64), nullable=False),
    sa.Column('provider_stream_id', sa.String(length=255), nullable=True),
    sa.Column('provider_playback_id', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewer_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('replay_asset_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('scheduled', 'live', 'ended', 'cancelled', 'failed')", name='ck_live_sessions_status'),
    sa.CheckConstraint("visibility IN ('public', 'followers')", name='ck_live_sessions_visibility'),
    sa.CheckConstraint('description IS NULL OR length(description) <= 5000', name='ck_live_sessions_description_length'),
    sa.CheckConstraint('ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at', name='ck_live_sessions_end_after_start'),
    sa.CheckConstraint('length(streaming_provider) > 0', name='ck_live_sessions_provider_nonempty'),
    sa.CheckConstraint('length(title) <= 255', name='ck_live_sessions_title_length'),
    sa.CheckConstraint('length(title) > 0', name='ck_live_sessions_title_nonempty'),
    sa.CheckConstraint('viewer_count >= 0', name='ck_live_sessions_viewer_count_nonnegative'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replay_asset_id'], ['media_assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_live_sessions_host_created', 'live_sessions', ['host_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_live_sessions_status_scheduled', 'live_sessions', ['status', 'scheduled_at'], unique=False)
    op.create_index('ix_live_sessions_status_started', 'live_sessions', ['status', 'started_at'], unique=False)
    op.create_table('media_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'uploading', 'completed', 'failed', 'expired')", name='ck_media_uploads_status'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_asset_id', name='uq_media_uploads_media_asset_id')
    )
    op.create_index('ix_media_uploads_status_expires_at', 'media_uploads', ['status', 'expires_at'], unique=False)
    op.create_table('post_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_post_media_position_nonnegative'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'media_asset_id', name='uq_post_media_post_asset'),
    sa.UniqueConstraint('post_id', 'position', name='uq_post_media_post_position')
    )
    op.create_index('ix_post_media_asset_id', 'post_media', ['media_asset_id'], unique=False)
    op.create_index('ix_post_media_post_position', 'post_media', ['post_id', 'position'], unique=False)
    op.create_table('reels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('video_asset_id', sa.UUID(), nullable=False),
    sa.Column('cover_asset_id', sa.UUID(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default='public', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("visibility IN ('public', 'followers')", name='ck_reels_visibility'),
    sa.CheckConstraint('caption IS NULL OR length(caption) <= 5000', name='ck_reels_caption_length'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cover_asset_id'], ['media_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['video_asset_id'], ['media_assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reels_author_created', 'reels', ['author_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_reels_created', 'reels', ['created_at', 'id'], unique=False)
    op.create_table('story_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_story_media_position_nonnegative'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'media_asset_id', name='uq_story_media_story_asset'),
    sa.UniqueConstraint('story_id', 'position', name='uq_story_media_story_position')
    )
    op.create_index('ix_story_media_asset_id', 'story_media', ['media_asset_id'], unique=False)
    op.create_index('ix_story_media_story_position', 'story_media', ['story_id', 'position'], unique=False)
    op.create_table('story_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reaction_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(reaction_type) > 0', name='ck_story_reactions_type_nonempty'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'user_id', name='uq_story_reactions_story_user')
    )
    op.create_index('ix_story_reactions_story_created', 'story_reactions', ['story_id', 'created_at'], unique=False)
    op.create_table('story_replies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(content) <= 5000', name='ck_story_replies_content_length'),
    sa.CheckConstraint('length(content) > 0', name='ck_story_replies_content_nonempty'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_story_replies_story_created', 'story_replies', ['story_id', 'created_at', 'id'], unique=False)
    op.create_table('story_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'viewer_id', name='uq_story_views_story_viewer')
    )
    op.create_index('ix_story_views_story_viewer', 'story_views', ['story_id', 'viewer_id'], unique=False)
    op.create_index('ix_story_views_viewer_viewed', 'story_views', ['viewer_id', 'viewed_at'], unique=False)
    op.create_table('reel_audio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reel_id', sa.UUID(), nullable=False),
    sa.Column('audio_asset_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('artist_name', sa.String(length=255), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_ms IS NULL OR end_ms > 0', name='ck_reel_audio_end_positive'),
    sa.CheckConstraint('start_ms IS NULL OR end_ms IS NULL OR end_ms > start_ms', name='ck_reel_audio_range'),
    sa.CheckConstraint('start_ms IS NULL OR start_ms >= 0', name='ck_reel_audio_start_nonnegative'),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['media_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reel_id', name='uq_reel_audio_reel')
    )
    op.create_index('ix_reel_audio_asset_id', 'reel_audio', ['audio_asset_id'], unique=False)
    op.create_table('reel_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reel_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(content) <= 5000', name='ck_reel_comments_content_length'),
    sa.CheckConstraint('length(content) > 0', name='ck_reel_comments_content_nonempty'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reel_comments_reel_created', 'reel_comments', ['reel_id', 'created_at', 'id'], unique=False)
    op.create_table('reel_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reel_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reel_id', 'user_id', name='uq_reel_likes_reel_user')
    )
    op.create_index('ix_reel_likes_reel_created', 'reel_likes', ['reel_id', 'created_at'], unique=False)
    op.create_index('ix_reel_likes_user_created', 'reel_likes', ['user_id', 'created_at'], unique=False)
    op.create_table('reel_saves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reel_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reel_id', 'user_id', name='uq_reel_saves_reel_user')
    )
    op.create_index('ix_reel_saves_reel_created', 'reel_saves', ['reel_id', 'created_at'], unique=False)
    op.create_index('ix_reel_saves_user_created', 'reel_saves', ['user_id', 'created_at'], unique=False)
    op.create_table('reel_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reel_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reel_shares_reel_created', 'reel_shares', ['reel_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_reel_shares_user_created', 'reel_shares', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reel_shares_user_created', table_name='reel_shares')
    op.drop_index('ix_reel_shares_reel_created', table_name='reel_shares')
    op.drop_table('reel_shares')
    op.drop_index('ix_reel_saves_user_created', table_name='reel_saves')
    op.drop_index('ix_reel_saves_reel_created', table_name='reel_saves')
    op.drop_table('reel_saves')
    op.drop_index('ix_reel_likes_user_created', table_name='reel_likes')
    op.drop_index('ix_reel_likes_reel_created', table_name='reel_likes')
    op.drop_table('reel_likes')
    op.drop_index('ix_reel_comments_reel_created', table_name='reel_comments')
    op.drop_table('reel_comments')
    op.drop_index('ix_reel_audio_asset_id', table_name='reel_audio')
    op.drop_table('reel_audio')
    op.drop_index('ix_story_views_viewer_viewed', table_name='story_views')
    op.drop_index('ix_story_views_story_viewer', table_name='story_views')
    op.drop_table('story_views')
    op.drop_index('ix_story_replies_story_created', table_name='story_replies')
    op.drop_table('story_replies')
    op.drop_index('ix_story_reactions_story_created', table_name='story_reactions')
    op.drop_table('story_reactions')
    op.drop_index('ix_story_media_story_position', table_name='story_media')
    op.drop_index('ix_story_media_asset_id', table_name='story_media')
    op.drop_table('story_media')
    op.drop_index('ix_reels_created', table_name='reels')
    op.drop_index('ix_reels_author_created', table_name='reels')
    op.drop_table('reels')
    op.drop_index('ix_post_media_post_position', table_name='post_media')
    op.drop_index('ix_post_media_asset_id', table_name='post_media')
    op.drop_table('post_media')
    op.drop_index('ix_media_uploads_status_expires_at', table_name='media_uploads')
    op.drop_table('media_uploads')
    op.drop_index('ix_live_sessions_status_started', table_name='live_sessions')
    op.drop_index('ix_live_sessions_status_scheduled', table_name='live_sessions')
    op.drop_index('ix_live_sessions_host_created', table_name='live_sessions')
    op.drop_table('live_sessions')
    op.drop_index('ix_stories_expires_at', table_name='stories')
    op.drop_index('ix_stories_author_created', table_name='stories')
    op.drop_table('stories')
    op.drop_index('ix_media_assets_status_created', table_name='media_assets')
    op.drop_index('ix_media_assets_owner_created', table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
