"""create social follow relationships

Revision ID: 816fbcf1a314
Revises: d10f35930eb0
Create Date: 2026-10-05 19:24:59.050581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816fbcf1a314'
down_revision: Union[str, Sequence[str], None] = 'd10f35930eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'rejected')", name='ck_follow_requests_status'),
    sa.CheckConstraint('requester_id <> target_id', name='ck_follow_requests_no_self_request'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'target_id', name='uq_follow_requests_requester_target')
    )
    op.create_index('ix_follow_requests_requester_status_created', 'follow_requests', ['requester_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_follow_requests_target_status_created', 'follow_requests', ['target_id', 'status', 'created_at'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id <> following_id', name='ck_follows_no_self_follow'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follows_follower_following')
    )
    op.create_index('ix_follows_follower_created', 'follows', ['follower_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_follows_following_created', 'follows', ['following_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_follows_following_created', table_name='follows')
    op.drop_index('ix_follows_follower_created', table_name='follows')
    op.drop_table('follows')
    op.drop_index('ix_follow_requests_target_status_created', table_name='follow_requests')
    op.drop_index('ix_follow_requests_requester_status_created', table_name='follow_requests')
    op.drop_table('follow_requests')
    # ### end Alembic commands ###
