"""create post comments

Revision ID: b26d579f5e88
Revises: 1f4a8c2d9b71
Create Date: 2026-10-07 14:11:43.965023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26d579f5e88'
down_revision: Union[str, Sequence[str], None] = '1f4a8c2d9b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(content) <= 1000', name='ck_post_comments_content_length'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_comments_post_created', 'post_comments', ['post_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_post_comments_user_created', 'post_comments', ['user_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_comments_user_created', table_name='post_comments')
    op.drop_index('ix_post_comments_post_created', table_name='post_comments')
    op.drop_table('post_comments')
    # ### end Alembic commands ###
