"""create profiles

Revision ID: d10f35930eb0
Revises: e3858e73e17f
Create Date: 2026-10-05 17:34:19.386689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10f35930eb0'
down_revision: Union[str, Sequence[str], None] = 'e3858e73e17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=2048), nullable=True),
    sa.Column('banner', sa.String(length=2048), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default='public', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('public', 'private')", name='ck_profiles_visibility'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_profiles_user_id'),
    sa.UniqueConstraint('username', name='uq_profiles_username')
    )
    op.create_index('ix_profiles_username', 'profiles', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profiles_username', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
