"""add profile verification timestamp

Revision ID: fda1ba1ddde6
Revises: b26d579f5e88
Create Date: 2026-10-08 03:54:53.861780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda1ba1ddde6'
down_revision: Union[str, Sequence[str], None] = 'b26d579f5e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'verified_at')
    # ### end Alembic commands ###
